<a href="https://colab.research.google.com/github/devan1510/devan1510/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import tenserflow
import tensorflow as tf
tf.__version__

'2.15.0'

In [ ]:
### creating tensors with tf.constant()
## create a scalar(rank 0 tensor)
scalar= tf.constant(15)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensins)
scalar.ndim

0

In [ ]:
### create a vector (tensor of 1 dimension)
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
## create a matrix(more than 1 dimension)
matrix= tf.constant(value=[[10,9],
                           [5,6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  9],
       [ 5,  6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix and define the datatype
matrix2= tf.constant([[2,3],
                      [5,6],
                      [7,8]],dtype= tf.float16)

In [ ]:
matrix2,matrix2.shape,matrix2.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[2., 3.],
        [5., 6.],
        [7., 8.]], dtype=float16)>,
 TensorShape([3, 2]),
 2)

In [ ]:
# create a tensor(n number of dimensions,technically all vectors and matrices are tensors)
tensor= tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# create the same tensor with tf.Variable() and tf.constant()
changable_tensor= tf.Variable([10,7])
unchangable_tensor= tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# elements in the constant tensor can not be edited or changed whereas, in the case of variable tensor elements can be edited
# to change an element in the variable tensor use assign() method
# here [] are used for indexing purposes
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
### creating random variables variables using tf.random
random1= tf.random.Generator.from_seed(42) # set the global seed for reproducibility
random1= random1.normal(shape= (3,2)) # create tensor from a normal distribution
random2= tf.random.Generator.from_seed(42)
random2= random2.normal(shape= (3,2))

In [ ]:
### shuffle given tensor elements amongst themselves
not_shuffled= tf.constant([[10,7],
                           [3,4],
                           [2,5]])

# get different arrangements of elements each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# other ways to make tensors in tensorflow

In [ ]:
# make a tensorof all ones and zeros
tf1= tf.ones(shape= (3,2))
tf0= tf.zeros(shape= (3,2))

In [ ]:
# create a tensor of rank(dimension) 4
rank4_tensor= tf.zeros([2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
## get various attributes of a tensor
print('datatype:',rank4_tensor.dtype)
print('dimensions(rank):',rank4_tensor.ndim)
print('shape:',rank4_tensor.shape)
print('elements along the first[0] axis:',rank4_tensor.shape[0])
print('elements along the last[-1] axis',rank4_tensor.shape[-1])
print('total no. of elements',tf.size(rank4_tensor).numpy()) # .nimpy() converts the output into a numpy array

datatype: <dtype: 'float32'>
dimensions(rank): 4
shape: (2, 3, 4, 5)
elements along the first[0] axis: 2
elements along the last[-1] axis 5
total no. of elements 120


# indexing in tensor flow is similar to python


In [ ]:
# get the first 2 elements of all the dimensions(rank)
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the dimension from each index except for the final one
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor(2 dimension)
rank2_tensor= tf.constant([[3,4],
                           [5,6]])
rank2_tensor.ndim

2

In [ ]:
# get the last item of each row as a numpy array
rank2_tensor[:,-1].numpy()

array([4, 6], dtype=int32)

# adding dimensions to the tensor while keeping the same information

In [ ]:
## add an extra dimension to 2 rank tensor(matrix)
rank3_tensor= rank2_tensor[...,tf.newaxis]
rank2_tensor.ndim,rank3_tensor.ndim

(2, 3)

In [ ]:
## the same can be done using tf.expand_dims()
tf.expand_dims(rank2_tensor,axis= -1)
## axis parameter is used to determine along which axis the new dimension must be added
## here,-1 means the last axis , 0 means the first axis and so long

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

# manipulating tensors

In [ ]:
# basic_operations
# add or subtract a scalar to a tensor
tensor= tf.constant([[3,4],
                     [5,6]])
tensor + 10,tensor - 10,

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 14],
        [15, 16]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-7, -6],
        [-5, -4]], dtype=int32)>)

In [ ]:
## use the multiply a tensor with a scalar
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [50, 60]], dtype=int32)>

In [ ]:
# note: upon being multiplied by a scalar the original tensor remains unchanged


# matrix multiplication in tenserflow







In [ ]:
## matrix multiplication using tf.matmul()
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 36],
       [45, 56]], dtype=int32)>

In [ ]:
# create a 3 x 2 tensor
X= tf.constant([[3,4],
                         [5,6],
                         [7,8]])

In [ ]:
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
Yt= tf.transpose(Y)
tf.matmul(X,Yt)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 53,  67,  81],
       [ 83, 105, 127],
       [113, 143, 173]], dtype=int32)>

# difference between tf.reshape() and tf.transpose()

In [ ]:
X,tf.transpose(X),tf.reshape(X,shape= (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 7],
        [4, 6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [6, 7, 8]], dtype=int32)>)

In [ ]:
X @ tf.transpose(X), X @ tf.reshape(X,shape= (2,3))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 25,  39,  53],
        [ 39,  61,  83],
        [ 53,  83, 113]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[33, 40, 47],
        [51, 62, 73],
        [69, 84, 99]], dtype=int32)>)

In [ ]:
# reshape the elements of a tensor using tf.reshape()
tf.reshape(X,shape= (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
# tf.transpose() is used to switch the dimension of the tensor
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [ ]:
# we can multiply two tensors X and Y using parameters
tf.matmul(a= X,b= Y,transpose_a= True,transpose_b= False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[143, 158],
       [170, 188]], dtype=int32)>

# the dot product(product of orthogonal projection of one vector upon another )

In [ ]:
## calculate the dot product on X and Y(requires X to be transposed)
tf.tensordot(tf.transpose(X),Y,axes= 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[143, 158],
       [170, 188]], dtype=int32)>

# changing the data type of tensor elements

In [ ]:
# create a new tensor with default datatype (float32)
B= tf.constant([1.7,7.4])

In [ ]:
# create a new tensor with default datatype(int32)
C= tf.constant([1,7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
# change from float32 to float16(reduced precision)
B= tf.cast(B,dtype= tf.float16)

In [ ]:
# change C from int32 to float32
C= tf.cast(C,dtype= tf.float16)

# get the absolute values using tf.abs()

In [ ]:
# create tensor with negative values
D= tf.constant([[-7,-10],
                [-6,-25]])
D

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -7, -10],
       [ -6, -25]], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 6, 25]], dtype=int32)>

# find the min,max,mean,sum(aggregation)

In [ ]:
# create a tensor with 50 random values between 0 and 100
import numpy as np
E= tf.constant(np.random.randint(low= 0,high= 100,size= 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 77, 20, 53, 11, 61, 39, 18, 10, 97, 69, 39, 97, 81, 98, 72, 32,
       87, 77, 91, 84, 20, 36, 29,  2, 30, 29, 13, 68, 81,  0, 94,  3, 48,
       44, 82, 67, 65,  3, 23, 33, 71, 37, 69, 69,  9,  8,  9, 58, 74])>

In [ ]:
# find the minimum using tf.reduce_min()
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# find the maximum using tf.reduce_max()
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# find the mean using tf.reduce_mean()
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
#find the sum tf.reduce_sum()
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2397>

# for standard deviation and variance use tfp.stats

In [ ]:
# first import tensorflow_probability(tfp)
# find the standard deviation
import tensorflow_probability as tfp
tf.cast(E,tf.float64)
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=944>

In [ ]:
E= tf.cast(E,dtype= tf.float32)
tfp.stats.stddev(E)

<tf.Tensor: shape=(), dtype=float32, numpy=30.726152>

In [ ]:
#finding positional maximum and minimum using tf.argmax() and tf.argmin()
a,b= tf.argmax(E).numpy(),tf.argmin(E).numpy()


# squeezing a tensor(removing all single dimensions(ranks))

In [ ]:
# remove single dimension using tf.squeeze()
# create a rank 5 tensor of 50 elements between 0 and 100
G= tf.constant(np.random.randint(0,100,50),shape= (1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
# squeeze tensor G(remove all 1 dimensions)
G_squeezed= tf.squeeze(G)
G_squeezed.shape,G_squeezed.ndim

(TensorShape([50]), 1)

# one hot encoding(numerical encoding to a categorical data)



In [ ]:
# create a list of indices
some_list= [0,1,2,3]
# one hot encode them
tf.one_hot(some_list, depth= 4) # this will encode the above list in the form of 1 and 0

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# square,log square_root
tf.square(some_list)# this will square every element in the tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

In [ ]:
some_list= tf.cast(some_list,dtype= tf.float32)
tf.sqrt(some_list)# find the sqrt of elements

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 1.       , 1.4142135, 1.7320508], dtype=float32)>

In [ ]:
H= tf.constant(np.arange(1,10))
H= tf.cast(H,dtype= tf.float32)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# manipulating tf.variable tensors

In [ ]:
# assign a particular value to a particular index of a variable tensor using .assign()
#create a variable tensor
I= tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
# assign the final value as 50
I.assign([0, 1, 2, 3,50]) # the change would be permanent

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# add a scalar to every element of a variable tensor using .assign_add()
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# tensors and numpy

In [ ]:
# tensors can be converted into numpy arrays using .numpy()
J= tf.constant(np.array(np.arange(0,5)))

In [ ]:
J.numpy()

array([0, 1, 2, 3, 4])

# tf.function()


In [ ]:
# create a function
def function(x,y):
  return x**2 +y
x= tf.constant(np.arange(0,10))
y= tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x**2 +y
tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>